import { quoteCategories } from './quote-categories';

export const mockFails: IFailItem[] = [
  {
    id: '1',
    title: 'AI Fail 1',
    description: 'AI Fail 1 description',
    categories: [quoteCategories[0], quoteCategories[1]],
    author: 'AI Fail 1 author',
    date: '2026-03-15',
    url: 'https://example.com/1',
  },
  {
    id: '2',
    title: 'AI Fail 2',
    description: 'AI Fail 2 description',
    categories: [quoteCategories[2], quoteCategories[3]],
    author: 'AI Fail 2 author',
    date: '2026-03-15',
    url: 'https://example.com/2',
  },
  {
    id: '3',
    title: 'AI Fail 3',
    description: 'AI Fail 3 description',
    categories: [quoteCategories[4], quoteCategories[5]],
    author: 'AI Fail 3 author',
    date: '2026-03-15',
    url: 'https://example.com/3',
  },
  {
    id: '4',
    title: 'AI Fail 4',
    description: 'AI Fail 4 description',
    categories: [quoteCategories[6], quoteCategories[7]],
    author: 'AI Fail 4 author',
    date: '2026-03-15',
    url: 'https://example.com/4',
  },
  {
    id: '5',
    title: 'AI Fail 5',
    description: 'AI Fail 5 description',
    categories: [quoteCategories[8], quoteCategories[9]],
    author: 'AI Fail 5 author',
    date: '2026-03-15',
    url: 'https://example.com/5',
  },
  {
    id: '6',
    title: 'AI Fail 6',
    description: 'AI Fail 6 description',
    categories: [quoteCategories[10], quoteCategories[11]],
    author: 'AI Fail 6 author',
    date: '2026-03-15',
    url: 'https://example.com/6',
  },
  {
    id: '7',
    title: 'AI Fail 7',
    description: 'AI Fail 7 description',
    categories: [quoteCategories[12], quoteCategories[13]],
    author: 'AI Fail 7 author',
    date: '2026-03-15',
    url: 'https://example.com/7',
  },
  {
    id: '8',
    title: 'AI Fail 8',
    description: 'AI Fail 8 description',
    categories: [quoteCategories[14], quoteCategories[15]],
    author: 'AI Fail 8 author',
    date: '2026-03-15',
    url: 'https://example.com/8',
  },
  {
    id: '9',
    title: 'AI Fail 9',
    description: 'AI Fail 9 description',
    categories: [quoteCategories[16], quoteCategories[17]],
    author: 'AI Fail 9 author',
    date: '2026-03-15',
    url: 'https://example.com/9',
  },
  {
    id: '10',
    title: 'AI Fail 10',
    description: 'AI Fail 10 description',
    categories: [quoteCategories[18], quoteCategories[19]],
    author: 'AI Fail 10 author',
    date: '2026-03-15',
    url: 'https://example.com/10',
  },
  {
    id: '11',
    title: 'AI Fail 11',
    description: 'AI Fail 11 description',
    categories: [quoteCategories[20], quoteCategories[21]],
    author: 'AI Fail 11 author',
    date: '2026-03-15',
    url: 'https://example.com/11',
  },
  {
    id: '12',
    title: 'AI Fail 12',
    description: 'AI Fail 12 description',
    categories: [quoteCategories[22], quoteCategories[23]],
    author: 'AI Fail 12 author',
    date: '2026-03-15',
    url: 'https://example.com/12',
  },

  {
    id: '13',
    title: 'AI Fail 13',
    description: 'AI Fail 13 description',
    categories: [quoteCategories[24], quoteCategories[25]],
    author: 'AI Fail 13 author',
    date: '2026-03-15',
    url: 'https://example.com/13',
  },
  {
    id: '14',
    title: 'AI Fail 14',
    description: 'AI Fail 14 description',
    categories: [quoteCategories[26], quoteCategories[27]],
    author: 'AI Fail 14 author',
    date: '2026-03-15',
    url: 'https://example.com/14',
  },
  {
    id: '15',
    title: 'AI Fail 15',
    description: 'AI Fail 15 description',
    categories: [quoteCategories[28], quoteCategories[29]],
    author: 'AI Fail 15 author',
    date: '2026-03-15',
    url: 'https://example.com/15',
  },
  {
    id: '16',
    title: 'AI Fail 16',
    description: 'AI Fail 16 description',
    categories: [quoteCategories[30], quoteCategories[31]],
    author: 'AI Fail 16 author',
    date: '2026-03-15',
    url: 'https://example.com/16',
  },
  {
    id: '17',
    title: 'AI Fail 17',
    description: 'AI Fail 17 description',
    categories: [quoteCategories[32], quoteCategories[33]],
    author: 'AI Fail 17 author',
    date: '2026-03-15',
    url: 'https://example.com/17',
  },
  {
    id: '18',
    title: 'AI Fail 18',
    description: 'AI Fail 18 description',
    categories: [quoteCategories[34], quoteCategories[35]],
    author: 'AI Fail 18 author',
    date: '2026-03-15',
    url: 'https://example.com/18',
  },
  {
    id: '19',
    title: 'AI Fail 19',
    description: 'AI Fail 19 description',
    categories: [quoteCategories[36], quoteCategories[37]],
    author: 'AI Fail 19 author',
    date: '2026-03-15',
    url: 'https://example.com/19',
  },
  {
    id: '20',
    title: 'AI Fail 20',
    description: 'AI Fail 20 description',
    categories: [quoteCategories[38], quoteCategories[39]],
    author: 'AI Fail 20 author',
    date: '2026-03-15',
    url: 'https://example.com/20',
  },
];
